### ISSUE TITLE
KeyError: 'csTimeZone'

### ISSUE THREAD

**Issue by marszip** [CommvaultEngg/cvpysdk#39]
Trying to get the SDK to work on RHEL 6 with python 3.5. 
But when I try to open a connection with Commcell, I get an keyerror on csTimeZone.

```
Please enter the Commcell Password:
Traceback (most recent call last):
  File "/home/myuser/.virtualenvs/commvault_toolbox/lib/python3.5/site-packages/cvpysdk/commcell.py", line 384, in _get_commserv_details
    self._commserv_timezone_name = response.json()['csTimeZone']['TimeZoneName']
KeyError: 'csTimeZone'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "./test.py", line 4, in <module>
    commcell = Commcell('mycommserver.local', 'mydomain\myuser')
  File "/home/myuser/.virtualenvs/commvault_toolbox/lib/python3.5/site-packages/cvpysdk/commcell.py", line 284, in __init__
    self.refresh()
  File "/home/myuser/.virtualenvs/commvault_toolbox/lib/python3.5/site-packages/cvpysdk/commcell.py", line 832, in refresh
    self._get_commserv_details()
  File "/home/myuser/.virtualenvs/commvault_toolbox/lib/python3.5/site-packages/cvpysdk/commcell.py", line 391, in _get_commserv_details
    raise SDKException('Commcell', '103', 'Key does not exist: {0}'.format(error))
cvpysdk.exception.SDKException: Failed to get the CommServ details
Key does not exist: 'csTimeZone'

```

My current Commvault version is 11 BUILD80.

**Comment by marszip** [comment]
Didn't realase you would need a client for the Python SDK. 
But on this server there is one installed. 

```
/opt/hds/Base64/HitachiHDS -status
--------------------------------- Instance001 ---------------------------------
[ General ]
 Version = 11(BUILD80) SP8
```

**Comment by GoelJatin** [comment]
The SDK does not require any Client, and it can be installed and run from any machine without any Commvault Package.

I was referring to the Service Pack installed on the machine with CommServ and WebServer packages installed.

My mistake, should've been more specific.

**Comment by marszip** [comment]
Took a while to get the version, this was SP8. But now in the meantime the commcell client is updated to SP10 and the SDK works now.

**Comment by GoelJatin** [comment]
We also just verified on an SP8 setup, and there is actually some new properties added to the SP10 API response, which were not available with SP8, which is why we saw this issue.

Please let us know if you see any other issues.
