### ISSUE TITLE
Error backing up Oracle RAC DB

### ISSUE THREAD

**Issue by ddill** [CommvaultEngg/cvpysdk#86]
I can backup a single instance Oracle DB but not RAC.

Here's the error:

Traceback (most recent call last):
  File "c:/Users/dbd9eb/python/full_backup_xxxx.py", line 27, in <module>
    rac_subclient = rac_backupset.subclients.get('ASC - Oracle (XXXX) RMAN Backups')
  File "C:\Users\dbd9eb\AppData\Local\Continuum\anaconda3\lib\site-packages\cvpysdk\subclient.py", line 739, in get
    if isinstance(self._subclients_dict[agent_name], list):
KeyError: 'oracle rac'

Thanks for your help!

**Comment by Vairavaprakash** [comment]
Hi Ddil,

Currently, we don't provide support for oracle RAC from SDK, please open a support ticket if this is needed
